### ISSUE TITLE
Composer conflicts with latest Silverstripe release

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-dynamodb#42]
This module has a conflict with the latest Silverstripe release for `guzzlehttp/psr7`.

```
$ composer create-project silverstripe/installer ./ss4
$ composer require silverstripe/dynamodb
```

Errors:

```
Problem 1
    - Conclusion: don't install silverstripe/dynamodb 4.0.2
    - Conclusion: don't install silverstripe/dynamodb 4.0.1
    - Conclusion: remove guzzlehttp/psr7 2.0.0
    - Installation request for silverstripe/dynamodb ^4.0 -> satisfiable by silverstripe/dynamodb[4.0.0, 4.0.1, 4.0.2].
    - Conclusion: don't install guzzlehttp/psr7 2.0.0
    - silverstripe/dynamodb 4.0.0 requires aws/aws-sdk-php ~3.18 -> satisfiable by aws/aws-sdk-php[3.100.0, 3.100.1,...., 3.99.4]
...
...
    - Can only install one of: guzzlehttp/psr7[1.1.0, 2.0.0].
```

### PRs
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/466

**Comment by emteknetnz** [comment]
Issue is that intervention/image (required by silverstripe/assets as `^2.3`) changed its requirement of guzzlehttp/psr7 in  from `~1.1` in [2.5.1](https://github.com/Intervention/image/blob/abbf18d5ab8367f96b3205ca3c89fb2fa598c69e/composer.json), to `~1.1 || ^2.0` in [2.6.0](https://github.com/Intervention/image/blob/a2d7238069bb01322f9c2a661449955434fec9c6/composer.json) which was released on 7 July 2021

I think there's only really a single solution for this

Change requirement of intervention/image in siverstripe/assets to `~2.5.1`.

A better longer term solution would be to update update silverstripe/dynamodb a more recent version of aws/aws-sdk-php that supports guzzlehttp/psr7.  However the most recent version [3.191.5](https://github.com/aws/aws-sdk-php/blob/c003e59f8976f6fe045c27f6afc5d5004317f39b/composer.json) released 27 August 2021 still only supports `^1.7` of guzzlehttp/psr7

**Comment by maxime-rainville** [comment]
What about we just tell people to run `composer require silverstripe/dynamodb --with-all-dependencies`? That downgraded my install of `guzzlehttp/psr7`to 1.1.

This is only going to be a problem for new project that add `silverstripe/dynamodb` after their initial set up. Existing project, won't have any problem because they will already be running `guzzlehttp/psr7` v1.1.

Resolving composer conflicts is not fun, but that's not something that should unphase the average PHP dev.

**Comment by emteknetnz** [comment]
~~I don't agree.~~  This would make silverstripe/dynamodb a special case module that needs has to be installed a different way from every other module.  There's also no reliable way to communicate to all developers and all platform support engineers that you need to this exact command.  Lots of people won't get these comms and just see this confusing composer error

It also blocks us adding dynamodb to any future sort of silverstripe/recipe-aws type of thing

**Comment by maxime-rainville** [comment]
Composer literally told me how to solve the problem in the error message. If we start doing this here, we're going to start doing it in a lot of other places because there's lots of unrelated libraries that rely on the same dependencies that occasionally clash.

Composer is perfectly capable of resolving these conflict itself. We should let it.

If `aws/aws-sdk-php` as a version that's compatible with `guzzlehttp/psr7` v2, we should upgrade to that. But otherwise I don't see this as a problem.

**Comment by emteknetnz** [comment]
Hmm I missed that same error message :-)

I've tried adding dynamodb to existing projects the following ways:

a) `composer require silverstripe/dynamodb` - error

b) `composer require silverstripe/dynamodb --with-all-dependencies` - resolves

c) Manually add `"silverstripe/dynamodb": "^4" to composer json` and run `composer update` resolves

This is a healthier long term solution rather than restricting the version in silverstripe/assets

**Comment by ChloeSartorelli** [comment]
No longer an issue
